/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AnnouncementRibbon: typeof import('./../src/components/Notify/AnnouncementRibbon.vue')['default']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ConcatCaptcha: typeof import('./../src/components/Captcha/ConcatCaptcha.vue')['default']
    ConfirmTextButton: typeof import('./../src/components/Button/ConfirmTextButton.vue')['default']
    CropperModal: typeof import('./../src/components/CropperModal/index.vue')['default']
    DeleteTextButton: typeof import('./../src/components/Button/DeleteTextButton.vue')['default']
    DictBadge: typeof import('./../src/components/Dict/display/DictBadge.vue')['default']
    DictCheckboxGroup: typeof import('./../src/components/Dict/group/DictCheckboxGroup.vue')['default']
    DictRadioGroup: typeof import('./../src/components/Dict/group/DictRadioGroup.vue')['default']
    DictSelect: typeof import('./../src/components/Dict/group/DictSelect.vue')['default']
    DictTag: typeof import('./../src/components/Dict/display/DictTag.vue')['default']
    DictTagGroup: typeof import('./../src/components/Dict/display/DictTagGroup.vue')['default']
    DictText: typeof import('./../src/components/Dict/display/DictText.vue')['default']
    Editor: typeof import('./../src/components/Editor/index.vue')['default']
    FileUpload: typeof import('./../src/components/Upload/FileUpload.vue')['default']
    IconSelector: typeof import('./../src/components/IconSelector/IconSelector.vue')['default']
    IconSelectorModal: typeof import('./../src/components/IconSelector/IconSelectorModal.vue')['default']
    Lov: typeof import('./../src/components/Lov/Lov.vue')['default']
    LovModal: typeof import('./../src/components/Lov/LovModal.vue')['default']
    LovSearch: typeof import('./../src/components/Lov/LovSearch.vue')['default']
    MarkedToHtml: typeof import('./../src/components/MarkedToHtml/MarkedToHtml.vue')['default']
    MultiLineEllipsis: typeof import('./../src/components/MultiLineEllipsis/index.vue')['default']
    OperationGroup: typeof import('./../src/components/Operation/OperationGroup.vue')['default']
    RotateCaptcha: typeof import('./../src/components/Captcha/RotateCaptcha.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchActions: typeof import('./../src/components/Search/SearchActions.vue')['default']
    SelectLanguage: typeof import('./../src/components/SelectLanguage/index.vue')['default']
    SliderCaptcha: typeof import('./../src/components/Captcha/SliderCaptcha.vue')['default']
    Spread: typeof import('./../src/components/MultiLineEllipsis/spread.vue')['default']
    TableOperateButton: typeof import('./../src/components/TableOperateButton/index.vue')['default']
    WordClickCaptcha: typeof import('./../src/components/Captcha/WordClickCaptcha.vue')['default']
  }
}
