export const siteLogoUrlMap = {
  'clean energy wire': 'Clean Energy Wire.png',
  cnbc: 'CNBC.png',
  'cpia-光伏热点新闻': 'CPIA-光伏热点新闻.png',
  'doe energy.gov': 'DOE Energy.Gov.png',
  err能研微讯: 'ERR能研微讯.png',
  'green tech media': 'Green Tech Media.png',
  iea: 'IEA.png',
  'infolink consulting': 'InfoLink Consulting.png',
  irena: 'IRENA.png',
  'pv magazine': 'PV magazine.png',
  'pv tech': 'PV Tech.png',
  'renew economy': 'Renew Economy.png',
  'renewable energy world': 'Renewable Energy World.png',
  reuters: 'Reuters.png',
  solarzoom: 'solarzoom.png',
  中国政府网: '中国政府网.png',
  中国电力企业联合会: '中国电力企业联合会.png',
  光伏們: '光伏們.png',
  光伏前沿: '光伏前沿.png',
  光伏在线: '光伏在线.png',
  光伏资讯: '光伏资讯.png',
  全球光伏: '全球光伏.png',
  北极星售电网: '北极星售电网.png',
  北极星太阳能光伏: '北极星太阳能光伏.png',
  华夏能源: '华夏能源.png',
  国家发改委: '国家发改委.png',
  国家能源局: '国家能源局.png',
  国际太阳能光伏网: '国际太阳能光伏网.png',
  工信部: '工信部.png',
  智汇光伏: '智汇光伏.png',
  电联新媒: '电联新媒.png',
  索比: '索比.png',
  能源一号: '能源一号.png',
  能源日参: '能源日参.png',
  落基山研究所: '落基山研究所.png',
  赶碳号科技: '赶碳号科技.png',
  钙钛矿太阳能电池: '钙钛矿太阳能电池.png',
  集邦新能源: '集邦新能源.png',
  黑鹰光伏: '黑鹰光伏.png',
  '中创碳投': '中创碳投.png',
}

export function getLogoUrlByName(name: string) {
  const url = siteLogoUrlMap[name.trim().toLowerCase()]
  return url ? `/logos/${url}` : new URL(`/src/assets/trinasolar-logo.png`, import.meta.url).href
}
